
version: "3"
services:
  codespace:
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - livy
    image: node:12.20.1
    volumes:
      - ../:/workspace:cached
  livy:
    image: jjgp/livy:4d8a912
    ports:
      - "127.0.0.1:8998:8998"